name: Linkcheck

on:
  workflow_dispatch:

jobs:
  linkcheck:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pip'

    - run: pip install -r requirements.txt

    - name: Check External Links
      run: |
        jupyter-book build book/ --builder linkcheck
