name: Spellcheck

on:
  workflow_dispatch:

jobs:
  spellcheck:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pip'

    - run: pip install -r requirements.txt

    # NOTE: this isn't a comprehensive spellcheck, just common typos
    - name: Spellcheck
      uses: codespell-project/actions-codespell@master
      with:
        check_filenames: true
        check_hidden: true
